"""Application-wide constants."""

APP_NAME = "Auditor Support Tool"
APP_VERSION = "0.1.0"

ORGANIZATION_NAME = "Auditor Support Tool"
ORGANIZATION_DOMAIN = "auditor-support-tool.local"

PRIMARY_ACCENT = "#81D185"

DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 760
MINIMUM_WINDOW_WIDTH = 950
MINIMUM_WINDOW_HEIGHT = 620