"""Application-wide constants."""

APP_NAME = "Auditor Support Tool"
APP_VERSION = "0.1.3-beta.1"
APP_EXECUTABLE_NAME = "Auditor Support Tool.exe"
UPDATER_EXECUTABLE_NAME = "Auditor Support Tool Updater.exe"
UPDATE_MANIFEST_NAME = "update-manifest.json"
UPDATE_HEALTH_TIMEOUT_SECONDS = 30
UPDATE_BACKUP_RETENTION = 2

GITHUB_REPOSITORY_OWNER = "Tumisang-Liphoto"
GITHUB_REPOSITORY_NAME = "Auditor_Support_Tool"
GITHUB_API_VERSION = "2022-11-28"

UPDATE_REQUEST_TIMEOUT_SECONDS = 30
UPDATE_PACKAGE_ASSET_NAME = "Auditor-Support-Tool-Windows-x64.zip"
UPDATE_CHECKSUM_ASSET_NAME = "Auditor-Support-Tool-Windows-x64.zip.sha256"

ORGANIZATION_NAME = "Auditor Support Tool"
ORGANIZATION_DOMAIN = "auditor-support-tool.local"

PRIMARY_ACCENT = "#81D185"

DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 760
MINIMUM_WINDOW_WIDTH = 950
MINIMUM_WINDOW_HEIGHT = 620
