"""Standard audit-field definitions used during field mapping."""

from dataclasses import dataclass

from auditor_support_tool.core.workbook_package import DatasetType


@dataclass(frozen=True, slots=True)
class StandardAuditField:
    """One standard field expected by later audit procedures."""

    key: str
    display_name: str
    description: str
    required: bool = False
    aliases: tuple[str, ...] = ()


GENERAL_LEDGER_FIELDS: tuple[StandardAuditField, ...] = (
    StandardAuditField(
        key="account_code",
        display_name="Account Code",
        description="Code of the general-ledger account affected by the entry.",
        required=False,
        aliases=("GL Account", "GL Code", "Account Number", "Ledger Account"),
    ),
    StandardAuditField(
        key="account_name",
        display_name="Account Name",
        description="Name or description of the general-ledger account.",
        required=False,
        aliases=("GL Account Name", "Ledger Account Name", "Account Description"),
    ),
    StandardAuditField(
        key="accounting_period",
        display_name="Accounting Period",
        description="Accounting period to which the transaction was assigned.",
        required=False,
        aliases=("Period", "Posting Period", "Accounting Month"),
    ),
    StandardAuditField(
        key="approval_date",
        display_name="Approval Date",
        description="Date on which the transaction or journal was approved.",
        required=False,
        aliases=("Approved Date", "Authorisation Date"),
    ),
    StandardAuditField(
        key="approval_status",
        display_name="Approval Status",
        description="Current approval state of the transaction or journal.",
        required=False,
        aliases=("Approval State", "Authorisation Status"),
    ),
    StandardAuditField(
        key="approval_timestamp",
        display_name="Approval Timestamp",
        description="System date and time when approval occurred.",
        required=False,
        aliases=("Approved At", "Approval Date Time"),
    ),
    StandardAuditField(
        key="approval_user",
        display_name="Approval User",
        description="User who approved or authorised the transaction or journal.",
        required=False,
        aliases=("Approved By", "Authorised By", "Approver"),
    ),
    StandardAuditField(
        key="batch_number",
        display_name="Batch Number",
        description="Identifier of the batch containing the transaction.",
        required=False,
        aliases=("Batch ID", "Batch Reference"),
    ),
    StandardAuditField(
        key="branch_code",
        display_name="Branch Code",
        description="Code identifying the branch associated with the transaction.",
        required=False,
        aliases=("Branch", "Office Code"),
    ),
    StandardAuditField(
        key="business_unit",
        display_name="Business Unit",
        description="Business unit responsible for or affected by the transaction.",
        required=False,
        aliases=("Business Area", "Operating Unit"),
    ),
    StandardAuditField(
        key="cost_centre_code",
        display_name="Cost Centre Code",
        description="Code identifying the cost centre charged or credited.",
        required=False,
        aliases=("Cost Center", "Cost Centre", "Cost Center Code"),
    ),
    StandardAuditField(
        key="cost_centre_name",
        display_name="Cost Centre Name",
        description="Name of the cost centre.",
        required=False,
        aliases=("Cost Center Name",),
    ),
    StandardAuditField(
        key="credit_amount",
        display_name="Credit Amount",
        description="Credit value of the accounting entry.",
        required=False,
        aliases=("Credit", "Cr Amount", "Credit Value"),
    ),
    StandardAuditField(
        key="currency",
        display_name="Currency",
        description="Currency code applicable to the transaction.",
        required=False,
        aliases=("Currency Code", "Transaction Currency"),
    ),
    StandardAuditField(
        key="customer_code",
        display_name="Customer Code",
        description="Identifier of the customer associated with the transaction.",
        required=False,
        aliases=("Customer ID", "Client Code", "Debtor Code"),
    ),
    StandardAuditField(
        key="customer_name",
        display_name="Customer Name",
        description="Name of the customer associated with the transaction.",
        required=False,
        aliases=("Client Name", "Debtor Name"),
    ),
    StandardAuditField(
        key="debit_amount",
        display_name="Debit Amount",
        description="Debit value of the accounting entry.",
        required=False,
        aliases=("Debit", "Dr Amount", "Debit Value"),
    ),
    StandardAuditField(
        key="department_code",
        display_name="Department Code",
        description="Code identifying the responsible department.",
        required=False,
        aliases=("Department", "Dept Code"),
    ),
    StandardAuditField(
        key="department_name",
        display_name="Department Name",
        description="Name of the responsible department.",
        required=False,
        aliases=("Dept Name",),
    ),
    StandardAuditField(
        key="document_number",
        display_name="Document Number",
        description="General source-document reference recorded in the ledger.",
        required=False,
        aliases=("Document No", "Doc Number", "Doc No", "Voucher Number"),
    ),
    StandardAuditField(
        key="document_type",
        display_name="Document Type",
        description="Classification of the source document.",
        required=False,
        aliases=("Doc Type", "Voucher Type"),
    ),
    StandardAuditField(
        key="employee_number",
        display_name="Employee Number",
        description="Employee or personnel identifier associated with the transaction.",
        required=False,
        aliases=("Employee No", "Emp No", "Employee ID", "Staff Number", "Personnel Number"),
    ),
    StandardAuditField(
        key="entry_timestamp",
        display_name="Entry Timestamp",
        description="System date and time when the entry was created or captured.",
        required=False,
        aliases=("Created At", "Entry Date Time", "Creation Timestamp"),
    ),
    StandardAuditField(
        key="entry_user",
        display_name="Entry User",
        description="User who initially entered or created the transaction.",
        required=False,
        aliases=("Entered By", "Created By", "Preparer", "Prepared By"),
    ),
    StandardAuditField(
        key="exchange_rate",
        display_name="Exchange Rate",
        description="Exchange rate applied to a foreign-currency transaction.",
        required=False,
        aliases=("FX Rate", "Conversion Rate"),
    ),
    StandardAuditField(
        key="financial_year",
        display_name="Financial Year",
        description="Financial year to which the transaction belongs.",
        required=False,
        aliases=("Fiscal Year", "Year"),
    ),
    StandardAuditField(
        key="fiscal_period",
        display_name="Fiscal Period",
        description="Fiscal month or reporting period used by the accounting system.",
        required=False,
        aliases=("Fiscal Month", "Reporting Period"),
    ),
    StandardAuditField(
        key="invoice_date",
        display_name="Invoice Date",
        description="Date appearing on the supplier or customer invoice.",
        required=False,
        aliases=("Inv Date", "Supplier Invoice Date"),
    ),
    StandardAuditField(
        key="invoice_number",
        display_name="Invoice Number",
        description="Invoice reference associated with the transaction.",
        required=False,
        aliases=("Invoice No", "Inv Number", "Inv No"),
    ),
    StandardAuditField(
        key="journal_number",
        display_name="Journal Number",
        description="Identifier grouping individual lines into one journal entry.",
        required=False,
        aliases=("Journal ID", "Journal No", "Voucher No", "Voucher ID"),
    ),
    StandardAuditField(
        key="journal_source",
        display_name="Journal Source",
        description="Module or source from which the journal originated.",
        required=False,
        aliases=("Source Module", "Journal Module", "Source"),
    ),
    StandardAuditField(
        key="journal_type",
        display_name="Journal Type",
        description="Classification such as manual, recurring, adjustment or system-generated.",
        required=False,
        aliases=("Entry Type", "Journal Category"),
    ),
    StandardAuditField(
        key="line_number",
        display_name="Line Number",
        description="Sequence number of the line within a journal or document.",
        required=False,
        aliases=("Journal Line Number", "Line No", "Item Number"),
    ),
    StandardAuditField(
        key="local_currency_amount",
        display_name="Local Currency Amount",
        description="Transaction amount converted to the entity's functional currency.",
        required=False,
        aliases=("Base Currency Amount", "Functional Currency Amount"),
    ),
    StandardAuditField(
        key="location_code",
        display_name="Location Code",
        description="Code identifying the location related to the transaction.",
        required=False,
        aliases=("Location", "Site Code"),
    ),
    StandardAuditField(
        key="posting_date",
        display_name="Posting Date",
        description="Date on which the transaction was posted to the ledger.",
        required=False,
        aliases=("Posted Date", "GL Date", "Ledger Date"),
    ),
    StandardAuditField(
        key="posting_status",
        display_name="Posting Status",
        description="Status such as posted, unposted, reversed or pending.",
        required=False,
        aliases=("Posted Status", "Journal Status"),
    ),
    StandardAuditField(
        key="posting_timestamp",
        display_name="Posting Timestamp",
        description="System date and time when posting occurred.",
        required=False,
        aliases=("Posted At", "Posting Date Time"),
    ),
    StandardAuditField(
        key="posting_user",
        display_name="Posting User",
        description="User who posted the transaction to the ledger.",
        required=False,
        aliases=("Posted By", "Poster"),
    ),
    StandardAuditField(
        key="purchase_order_number",
        display_name="Purchase Order Number",
        description="Purchase-order reference linked to the transaction.",
        required=False,
        aliases=("PO Number", "PO No", "Purchase Order"),
    ),
    StandardAuditField(
        key="reference_number",
        display_name="Reference Number",
        description="Additional transaction reference not otherwise classified.",
        required=False,
        aliases=("Reference", "Ref Number", "External Reference"),
    ),
    StandardAuditField(
        key="reversal_date",
        display_name="Reversal Date",
        description="Date on which the transaction was or will be reversed.",
        required=False,
        aliases=("Reversed Date",),
    ),
    StandardAuditField(
        key="reversal_indicator",
        display_name="Reversal Indicator",
        description="Indicates whether the transaction is a reversal or has been reversed.",
        required=False,
        aliases=("Is Reversal", "Reversal Flag"),
    ),
    StandardAuditField(
        key="reversal_reference",
        display_name="Reversal Reference",
        description="Reference linking the original entry and its reversal.",
        required=False,
        aliases=("Reversal Document", "Original Journal Reference"),
    ),
    StandardAuditField(
        key="source_system",
        display_name="Source System",
        description="System from which the transaction originated.",
        required=False,
        aliases=("Originating System", "System Source"),
    ),
    StandardAuditField(
        key="transaction_amount",
        display_name="Transaction Amount",
        description="Signed or single-column monetary value of the transaction.",
        required=False,
        aliases=("Amount", "Net Amount", "Value", "Transaction Value"),
    ),
    StandardAuditField(
        key="transaction_date",
        display_name="Transaction Date",
        description="Date on which the underlying business transaction occurred.",
        required=False,
        aliases=("Doc Date", "Document Date", "Transaction Dt", "Effective Date"),
    ),
    StandardAuditField(
        key="transaction_description",
        display_name="Transaction Description",
        description="Narrative or explanation recorded for the transaction.",
        required=False,
        aliases=("Description", "Narration", "Memo", "Journal Description"),
    ),
    StandardAuditField(
        key="transaction_id",
        display_name="Transaction ID",
        description="Unique identifier assigned to the individual transaction or ledger line.",
        required=False,
        aliases=("Transaction Number", "Transaction No", "Record ID"),
    ),
    StandardAuditField(
        key="transaction_type",
        display_name="Transaction Type",
        description="Classification of the transaction.",
        required=False,
        aliases=("Entry Category", "Transaction Category"),
    ),
    StandardAuditField(
        key="user_id",
        display_name="User ID",
        description="Generic user identifier where the extract does not distinguish user roles.",
        required=False,
        aliases=("Username", "User", "Operator ID"),
    ),
    StandardAuditField(
        key="vendor_code",
        display_name="Vendor Code",
        description="Identifier of the supplier associated with the transaction.",
        required=False,
        aliases=("Vendor ID", "Supplier Code", "Supplier ID"),
    ),
    StandardAuditField(
        key="vendor_name",
        display_name="Vendor Name",
        description="Name of the supplier associated with the transaction.",
        required=False,
        aliases=("Supplier Name", "Payee Name"),
    ),
)

CHART_OF_ACCOUNTS_FIELDS: tuple[StandardAuditField, ...] = (
    StandardAuditField(
        key="account_category",
        display_name="Account Category",
        description="Broad financial classification of the account.",
        required=False,
        aliases=("Category", "Financial Category"),
    ),
    StandardAuditField(
        key="account_class",
        display_name="Account Class",
        description="Entity-specific classification of the account.",
        required=False,
        aliases=("Class",),
    ),
    StandardAuditField(
        key="account_code",
        display_name="Account Code",
        description="Unique code assigned to the account.",
        required=False,
        aliases=("GL Code", "Account Number"),
    ),
    StandardAuditField(
        key="account_description",
        display_name="Account Description",
        description="Detailed explanation of the purpose of the account.",
        required=False,
        aliases=("Description", "Purpose"),
    ),
    StandardAuditField(
        key="account_group",
        display_name="Account Group",
        description="Reporting or operational group to which the account belongs.",
        required=False,
        aliases=("Group",),
    ),
    StandardAuditField(
        key="account_level",
        display_name="Account Level",
        description="Hierarchical level of the account.",
        required=False,
        aliases=("Level", "Hierarchy Level"),
    ),
    StandardAuditField(
        key="account_name",
        display_name="Account Name",
        description="Formal name of the account.",
        required=False,
        aliases=("GL Account Name", "Name"),
    ),
    StandardAuditField(
        key="account_status",
        display_name="Account Status",
        description="Status such as active, inactive, blocked or closed.",
        required=False,
        aliases=("Active Status", "Status"),
    ),
    StandardAuditField(
        key="account_type",
        display_name="Account Type",
        description="Detailed account classification used by the accounting system.",
        required=False,
        aliases=("Type",),
    ),
    StandardAuditField(
        key="active_date",
        display_name="Active Date",
        description="Date from which the account became available for use.",
        required=False,
        aliases=("Effective Date", "Start Date"),
    ),
    StandardAuditField(
        key="allow_direct_posting",
        display_name="Allow Direct Posting",
        description="Indicates whether transactions may be posted directly to the account.",
        required=False,
        aliases=("Direct Posting",),
    ),
    StandardAuditField(
        key="allow_manual_journals",
        display_name="Allow Manual Journals",
        description="Indicates whether manual journals are permitted.",
        required=False,
        aliases=("Manual Posting Allowed",),
    ),
    StandardAuditField(
        key="balance_sheet_indicator",
        display_name="Balance Sheet Indicator",
        description="Identifies whether the account is a balance-sheet account.",
        required=False,
        aliases=("BS Indicator",),
    ),
    StandardAuditField(
        key="branch_code",
        display_name="Branch Code",
        description="Branch to which the account is assigned.",
        required=False,
        aliases=("Branch",),
    ),
    StandardAuditField(
        key="budget_control_indicator",
        display_name="Budget Control Indicator",
        description="Indicates whether budget controls apply.",
        required=False,
        aliases=("Budget Controlled",),
    ),
    StandardAuditField(
        key="business_unit",
        display_name="Business Unit",
        description="Business unit associated with the account.",
        required=False,
        aliases=("Business Area",),
    ),
    StandardAuditField(
        key="closing_date",
        display_name="Closing Date",
        description="Date on which the account was closed or deactivated.",
        required=False,
        aliases=("Closed Date",),
    ),
    StandardAuditField(
        key="consolidation_account_code",
        display_name="Consolidation Account Code",
        description="Corresponding account used for group consolidation.",
        required=False,
        aliases=("Group Account Code",),
    ),
    StandardAuditField(
        key="cost_centre_required",
        display_name="Cost Centre Required",
        description="Indicates whether a cost centre is mandatory.",
        required=False,
        aliases=("Cost Center Required",),
    ),
    StandardAuditField(
        key="created_by",
        display_name="Created By",
        description="User who created the account.",
        required=False,
        aliases=("Creator",),
    ),
    StandardAuditField(
        key="creation_date",
        display_name="Creation Date",
        description="Date on which the account was created.",
        required=False,
        aliases=("Created Date",),
    ),
    StandardAuditField(
        key="currency",
        display_name="Currency",
        description="Currency assigned or restricted to the account.",
        required=False,
        aliases=("Currency Code",),
    ),
    StandardAuditField(
        key="department_code",
        display_name="Department Code",
        description="Department responsible for the account.",
        required=False,
        aliases=("Department",),
    ),
    StandardAuditField(
        key="financial_statement_group",
        display_name="Financial Statement Group",
        description="Reporting group used in the financial statements.",
        required=False,
        aliases=("FS Group",),
    ),
    StandardAuditField(
        key="financial_statement_line",
        display_name="Financial Statement Line",
        description="Financial-statement line to which the account maps.",
        required=False,
        aliases=("FS Line",),
    ),
    StandardAuditField(
        key="inactive_date",
        display_name="Inactive Date",
        description="Date from which the account ceased to be active.",
        required=False,
        aliases=("Deactivation Date",),
    ),
    StandardAuditField(
        key="modified_by",
        display_name="Modified By",
        description="User who last changed the account record.",
        required=False,
        aliases=("Last Updated By",),
    ),
    StandardAuditField(
        key="modification_date",
        display_name="Modification Date",
        description="Date of the most recent account change.",
        required=False,
        aliases=("Last Modified Date", "Updated Date"),
    ),
    StandardAuditField(
        key="normal_balance",
        display_name="Normal Balance",
        description="Expected debit or credit nature of the account.",
        required=False,
        aliases=("Debit Credit Nature",),
    ),
    StandardAuditField(
        key="parent_account_code",
        display_name="Parent Account Code",
        description="Code of the immediate parent account.",
        required=False,
        aliases=("Parent Account", "Control Account"),
    ),
    StandardAuditField(
        key="posting_account_indicator",
        display_name="Posting Account Indicator",
        description="Identifies whether the account accepts postings.",
        required=False,
        aliases=("Posting Account",),
    ),
    StandardAuditField(
        key="reconciliation_account_indicator",
        display_name="Reconciliation Account Indicator",
        description="Identifies an account linked to a subsidiary ledger.",
        required=False,
        aliases=("Reconciliation Account",),
    ),
    StandardAuditField(
        key="reporting_code",
        display_name="Reporting Code",
        description="Alternative code used for reporting.",
        required=False,
        aliases=("Report Code",),
    ),
    StandardAuditField(
        key="tax_code_required",
        display_name="Tax Code Required",
        description="Indicates whether a tax code is mandatory.",
        required=False,
        aliases=("Tax Required",),
    ),
)

TRIAL_BALANCE_FIELDS: tuple[StandardAuditField, ...] = (
    StandardAuditField(
        key="account_category",
        display_name="Account Category",
        description="Financial classification of the account.",
        required=False,
        aliases=("Category",),
    ),
    StandardAuditField(
        key="account_code",
        display_name="Account Code",
        description="Code identifying the general-ledger account.",
        required=False,
        aliases=("GL Code", "Account Number"),
    ),
    StandardAuditField(
        key="account_name",
        display_name="Account Name",
        description="Name of the general-ledger account.",
        required=False,
        aliases=("GL Account Name",),
    ),
    StandardAuditField(
        key="accounting_period",
        display_name="Accounting Period",
        description="Accounting period represented by the balance.",
        required=False,
        aliases=("Period",),
    ),
    StandardAuditField(
        key="adjusted_credit_balance",
        display_name="Adjusted Credit Balance",
        description="Credit balance after adjustments.",
        required=False,
        aliases=("Adjusted Credit",),
    ),
    StandardAuditField(
        key="adjusted_debit_balance",
        display_name="Adjusted Debit Balance",
        description="Debit balance after adjustments.",
        required=False,
        aliases=("Adjusted Debit",),
    ),
    StandardAuditField(
        key="adjustment_credit",
        display_name="Adjustment Credit",
        description="Credit adjustment applied to the balance.",
        required=False,
        aliases=("Credit Adjustment",),
    ),
    StandardAuditField(
        key="adjustment_debit",
        display_name="Adjustment Debit",
        description="Debit adjustment applied to the balance.",
        required=False,
        aliases=("Debit Adjustment",),
    ),
    StandardAuditField(
        key="branch_code",
        display_name="Branch Code",
        description="Branch associated with the balance.",
        required=False,
        aliases=("Branch",),
    ),
    StandardAuditField(
        key="business_unit",
        display_name="Business Unit",
        description="Business unit associated with the balance.",
        required=False,
        aliases=("Business Area",),
    ),
    StandardAuditField(
        key="closing_balance",
        display_name="Closing Balance",
        description="Signed closing balance of the account.",
        required=False,
        aliases=("Ending Balance", "Final Balance"),
    ),
    StandardAuditField(
        key="closing_credit_balance",
        display_name="Closing Credit Balance",
        description="Credit component of the closing balance.",
        required=False,
        aliases=("Closing Credit",),
    ),
    StandardAuditField(
        key="closing_debit_balance",
        display_name="Closing Debit Balance",
        description="Debit component of the closing balance.",
        required=False,
        aliases=("Closing Debit",),
    ),
    StandardAuditField(
        key="cost_centre_code",
        display_name="Cost Centre Code",
        description="Cost centre associated with the balance.",
        required=False,
        aliases=("Cost Center", "Cost Centre"),
    ),
    StandardAuditField(
        key="credit_movement",
        display_name="Credit Movement",
        description="Total credit activity during the period.",
        required=False,
        aliases=("Period Credits", "Credit Turnover"),
    ),
    StandardAuditField(
        key="currency",
        display_name="Currency",
        description="Currency in which balances are reported.",
        required=False,
        aliases=("Currency Code",),
    ),
    StandardAuditField(
        key="debit_movement",
        display_name="Debit Movement",
        description="Total debit activity during the period.",
        required=False,
        aliases=("Period Debits", "Debit Turnover"),
    ),
    StandardAuditField(
        key="department_code",
        display_name="Department Code",
        description="Department associated with the balance.",
        required=False,
        aliases=("Department",),
    ),
    StandardAuditField(
        key="financial_statement_group",
        display_name="Financial Statement Group",
        description="Financial-statement grouping assigned to the account.",
        required=False,
        aliases=("FS Group",),
    ),
    StandardAuditField(
        key="financial_statement_line",
        display_name="Financial Statement Line",
        description="Financial-statement line to which the balance maps.",
        required=False,
        aliases=("FS Line",),
    ),
    StandardAuditField(
        key="financial_year",
        display_name="Financial Year",
        description="Financial year represented by the trial balance.",
        required=False,
        aliases=("Fiscal Year", "Year"),
    ),
    StandardAuditField(
        key="fiscal_period",
        display_name="Fiscal Period",
        description="Fiscal period represented by the trial balance.",
        required=False,
        aliases=("Fiscal Month",),
    ),
    StandardAuditField(
        key="location_code",
        display_name="Location Code",
        description="Location associated with the balance.",
        required=False,
        aliases=("Location", "Site Code"),
    ),
    StandardAuditField(
        key="opening_balance",
        display_name="Opening Balance",
        description="Signed balance at the beginning of the period.",
        required=False,
        aliases=("Beginning Balance", "Start Balance"),
    ),
    StandardAuditField(
        key="opening_credit_balance",
        display_name="Opening Credit Balance",
        description="Credit component of the opening balance.",
        required=False,
        aliases=("Opening Credit",),
    ),
    StandardAuditField(
        key="opening_debit_balance",
        display_name="Opening Debit Balance",
        description="Debit component of the opening balance.",
        required=False,
        aliases=("Opening Debit",),
    ),
    StandardAuditField(
        key="period_end_date",
        display_name="Period End Date",
        description="Final date of the reporting period.",
        required=False,
        aliases=("End Date", "Reporting Date"),
    ),
    StandardAuditField(
        key="period_start_date",
        display_name="Period Start Date",
        description="First date of the reporting period.",
        required=False,
        aliases=("Start Date",),
    ),
    StandardAuditField(
        key="prior_year_closing_balance",
        display_name="Prior-Year Closing Balance",
        description="Comparative closing balance from the preceding year.",
        required=False,
        aliases=("Previous Year Balance", "PY Closing Balance"),
    ),
    StandardAuditField(
        key="prior_year_credit_balance",
        display_name="Prior-Year Credit Balance",
        description="Prior-year credit balance.",
        required=False,
        aliases=("PY Credit",),
    ),
    StandardAuditField(
        key="prior_year_debit_balance",
        display_name="Prior-Year Debit Balance",
        description="Prior-year debit balance.",
        required=False,
        aliases=("PY Debit",),
    ),
    StandardAuditField(
        key="reporting_entity",
        display_name="Reporting Entity",
        description="Entity or company represented by the trial balance.",
        required=False,
        aliases=("Company", "Entity"),
    ),
    StandardAuditField(
        key="unadjusted_credit_balance",
        display_name="Unadjusted Credit Balance",
        description="Credit balance before adjustments.",
        required=False,
        aliases=("Unadjusted Credit",),
    ),
    StandardAuditField(
        key="unadjusted_debit_balance",
        display_name="Unadjusted Debit Balance",
        description="Debit balance before adjustments.",
        required=False,
        aliases=("Unadjusted Debit",),
    ),
)

EMPLOYEE_MASTER_FIELDS: tuple[StandardAuditField, ...] = (
    StandardAuditField(
        key="active_status",
        display_name="Active Status",
        description="Indicates whether the employee is currently active.",
        required=False,
        aliases=("Active", "Is Active"),
    ),
    StandardAuditField(
        key="annual_salary",
        display_name="Annual Salary",
        description="Employee's annual base salary.",
        required=False,
        aliases=("Yearly Salary", "Annual Basic"),
    ),
    StandardAuditField(
        key="bank_account_name",
        display_name="Bank Account Name",
        description="Name registered against the employee's bank account.",
        required=False,
        aliases=("Account Holder",),
    ),
    StandardAuditField(
        key="bank_account_number",
        display_name="Bank Account Number",
        description="Employee bank-account identifier.",
        required=False,
        aliases=("Bank Account", "Account Number"),
    ),
    StandardAuditField(
        key="bank_branch_code",
        display_name="Bank Branch Code",
        description="Branch or clearing code for the employee's bank account.",
        required=False,
        aliases=("Branch Code", "Sort Code"),
    ),
    StandardAuditField(
        key="bank_name",
        display_name="Bank Name",
        description="Name of the employee's bank.",
        required=False,
        aliases=("Bank",),
    ),
    StandardAuditField(
        key="basic_salary",
        display_name="Basic Salary",
        description="Employee's regular base salary.",
        required=False,
        aliases=("Base Salary", "Basic Pay"),
    ),
    StandardAuditField(
        key="birth_date",
        display_name="Birth Date",
        description="Employee's date of birth.",
        required=False,
        aliases=("Date of Birth", "DOB"),
    ),
    StandardAuditField(
        key="branch_code",
        display_name="Branch Code",
        description="Organisational branch to which the employee is assigned.",
        required=False,
        aliases=("Branch", "Office Code"),
    ),
    StandardAuditField(
        key="business_unit",
        display_name="Business Unit",
        description="Business unit to which the employee belongs.",
        required=False,
        aliases=("Business Area",),
    ),
    StandardAuditField(
        key="contract_end_date",
        display_name="Contract End Date",
        description="Date on which a fixed-term contract ends.",
        required=False,
        aliases=("Contract Expiry Date",),
    ),
    StandardAuditField(
        key="contract_start_date",
        display_name="Contract Start Date",
        description="Date on which the employment contract commenced.",
        required=False,
        aliases=("Contract Commencement Date",),
    ),
    StandardAuditField(
        key="contract_type",
        display_name="Contract Type",
        description="Classification such as permanent, temporary or fixed-term.",
        required=False,
        aliases=("Employment Type",),
    ),
    StandardAuditField(
        key="cost_centre_code",
        display_name="Cost Centre Code",
        description="Cost centre to which employee costs are allocated.",
        required=False,
        aliases=("Cost Center", "Cost Centre"),
    ),
    StandardAuditField(
        key="cost_centre_name",
        display_name="Cost Centre Name",
        description="Name of the employee's assigned cost centre.",
        required=False,
        aliases=("Cost Center Name",),
    ),
    StandardAuditField(
        key="created_by",
        display_name="Created By",
        description="User who created the employee record.",
        required=False,
        aliases=("Creator",),
    ),
    StandardAuditField(
        key="creation_date",
        display_name="Creation Date",
        description="Date on which the employee record was created.",
        required=False,
        aliases=("Created Date",),
    ),
    StandardAuditField(
        key="department_code",
        display_name="Department Code",
        description="Code of the employee's department.",
        required=False,
        aliases=("Department", "Dept Code"),
    ),
    StandardAuditField(
        key="department_name",
        display_name="Department Name",
        description="Name of the employee's department.",
        required=False,
        aliases=("Dept Name",),
    ),
    StandardAuditField(
        key="email_address",
        display_name="Email Address",
        description="Employee's official or recorded email address.",
        required=False,
        aliases=("Email", "Work Email"),
    ),
    StandardAuditField(
        key="employee_category",
        display_name="Employee Category",
        description="Employee grouping such as management or support staff.",
        required=False,
        aliases=("Staff Category",),
    ),
    StandardAuditField(
        key="employee_id",
        display_name="Employee ID",
        description="Unique employee identifier.",
        required=False,
        aliases=("Employee Number", "Emp No", "Staff ID", "Personnel Number"),
    ),
    StandardAuditField(
        key="employee_name",
        display_name="Employee Name",
        description="Employee's full name where stored in one field.",
        required=False,
        aliases=("Full Name", "Staff Name"),
    ),
    StandardAuditField(
        key="employment_status",
        display_name="Employment Status",
        description="Detailed employment state such as active, suspended or terminated.",
        required=False,
        aliases=("Employee Status", "Status"),
    ),
    StandardAuditField(
        key="first_name",
        display_name="First Name",
        description="Employee's given name.",
        required=False,
        aliases=("Given Name", "Forename"),
    ),
    StandardAuditField(
        key="gender",
        display_name="Gender",
        description="Gender value recorded in the employee master.",
        required=False,
        aliases=("Sex",),
    ),
    StandardAuditField(
        key="grade",
        display_name="Grade",
        description="Employee's organisational grade.",
        required=False,
        aliases=("Job Grade",),
    ),
    StandardAuditField(
        key="hire_date",
        display_name="Hire Date",
        description="Date on which the employee commenced employment.",
        required=False,
        aliases=("Employment Date", "Date Hired", "Start Date"),
    ),
    StandardAuditField(
        key="identification_number",
        display_name="Identification Number",
        description="National identity or other official identification number.",
        required=False,
        aliases=("National ID", "ID Number", "Passport Number"),
    ),
    StandardAuditField(
        key="job_title",
        display_name="Job Title",
        description="Employee's position or role title.",
        required=False,
        aliases=("Position", "Designation"),
    ),
    StandardAuditField(
        key="last_name",
        display_name="Last Name",
        description="Employee's family or surname.",
        required=False,
        aliases=("Surname", "Family Name"),
    ),
    StandardAuditField(
        key="location_code",
        display_name="Location Code",
        description="Code identifying the employee's normal work location.",
        required=False,
        aliases=("Location", "Site Code"),
    ),
    StandardAuditField(
        key="manager_employee_id",
        display_name="Manager Employee ID",
        description="Employee ID of the employee's manager.",
        required=False,
        aliases=("Supervisor ID", "Manager ID"),
    ),
    StandardAuditField(
        key="manager_name",
        display_name="Manager Name",
        description="Name of the employee's manager.",
        required=False,
        aliases=("Supervisor Name", "Reports To"),
    ),
    StandardAuditField(
        key="middle_name",
        display_name="Middle Name",
        description="Employee's middle or additional names.",
        required=False,
        aliases=("Other Names",),
    ),
    StandardAuditField(
        key="modified_by",
        display_name="Modified By",
        description="User who last changed the employee record.",
        required=False,
        aliases=("Last Updated By",),
    ),
    StandardAuditField(
        key="modification_date",
        display_name="Modification Date",
        description="Date of the latest employee-record change.",
        required=False,
        aliases=("Last Modified Date", "Updated Date"),
    ),
    StandardAuditField(
        key="monthly_salary",
        display_name="Monthly Salary",
        description="Employee's standard monthly base salary.",
        required=False,
        aliases=("Monthly Basic",),
    ),
    StandardAuditField(
        key="nationality",
        display_name="Nationality",
        description="Nationality recorded for the employee.",
        required=False,
        aliases=("Citizenship",),
    ),
    StandardAuditField(
        key="payroll_number",
        display_name="Payroll Number",
        description="Identifier used by the payroll system.",
        required=False,
        aliases=("Payroll ID", "Pay Number"),
    ),
    StandardAuditField(
        key="payment_method",
        display_name="Payment Method",
        description="Method used to pay the employee.",
        required=False,
        aliases=("Pay Method",),
    ),
    StandardAuditField(
        key="pension_number",
        display_name="Pension Number",
        description="Employee's pension or retirement-fund identifier.",
        required=False,
        aliases=("Retirement Number",),
    ),
    StandardAuditField(
        key="phone_number",
        display_name="Phone Number",
        description="Employee contact telephone number.",
        required=False,
        aliases=("Telephone", "Mobile Number", "Contact Number"),
    ),
    StandardAuditField(
        key="position_code",
        display_name="Position Code",
        description="Code identifying the employee's approved position.",
        required=False,
        aliases=("Post Number", "Position ID"),
    ),
    StandardAuditField(
        key="salary_grade",
        display_name="Salary Grade",
        description="Grade or scale used to determine remuneration.",
        required=False,
        aliases=("Pay Grade", "Salary Scale"),
    ),
    StandardAuditField(
        key="tax_number",
        display_name="Tax Number",
        description="Employee's tax-registration identifier.",
        required=False,
        aliases=("Tax ID", "TIN"),
    ),
    StandardAuditField(
        key="termination_date",
        display_name="Termination Date",
        description="Date on which employment ended.",
        required=False,
        aliases=("Exit Date", "Separation Date"),
    ),
    StandardAuditField(
        key="termination_reason",
        display_name="Termination Reason",
        description="Recorded reason for the employee's termination.",
        required=False,
        aliases=("Exit Reason",),
    ),
    StandardAuditField(
        key="user_account_id",
        display_name="User Account ID",
        description="System account linked to the employee.",
        required=False,
        aliases=("Username", "Network ID", "Login ID"),
    ),
    StandardAuditField(
        key="work_location",
        display_name="Work Location",
        description="Name or description of the employee's normal workplace.",
        required=False,
        aliases=("Duty Station", "Office Location"),
    ),
)

VENDOR_MASTER_FIELDS: tuple[StandardAuditField, ...] = (
    StandardAuditField(
        "vendor_code",
        "Vendor Code",
        "Unique supplier or vendor identifier.",
        False,
        ("Vendor ID", "Supplier Code"),
    ),
    StandardAuditField(
        "vendor_name",
        "Vendor Name",
        "Registered supplier or vendor name.",
        False,
        ("Supplier Name",),
    ),
)
CUSTOMER_MASTER_FIELDS: tuple[StandardAuditField, ...] = (
    StandardAuditField(
        "customer_code",
        "Customer Code",
        "Unique customer identifier.",
        False,
        ("Customer ID", "Client Code"),
    ),
    StandardAuditField(
        "customer_name", "Customer Name", "Registered customer name.", False, ("Client Name",)
    ),
)
USER_ACCESS_FIELDS: tuple[StandardAuditField, ...] = (
    StandardAuditField(
        "user_id",
        "User ID",
        "Unique application or database user identifier.",
        False,
        ("Username", "Login ID"),
    ),
    StandardAuditField(
        "role",
        "Role",
        "Role or access group assigned to the user.",
        False,
        ("Access Role", "Group"),
    ),
)

FIELD_CATALOGUES: dict[DatasetType, tuple[StandardAuditField, ...]] = {
    DatasetType.GENERAL_LEDGER: GENERAL_LEDGER_FIELDS,
    DatasetType.JOURNAL_LISTING: GENERAL_LEDGER_FIELDS,
    DatasetType.CHART_OF_ACCOUNTS: CHART_OF_ACCOUNTS_FIELDS,
    DatasetType.TRIAL_BALANCE: TRIAL_BALANCE_FIELDS,
    DatasetType.EMPLOYEE_MASTER: EMPLOYEE_MASTER_FIELDS,
    DatasetType.VENDOR_MASTER: VENDOR_MASTER_FIELDS,
    DatasetType.CUSTOMER_MASTER: CUSTOMER_MASTER_FIELDS,
    DatasetType.USER_ACCESS_LISTING: USER_ACCESS_FIELDS,
}


def fields_for_dataset_type(
    dataset_type: DatasetType,
) -> tuple[StandardAuditField, ...]:
    """Return alphabetically ordered fields for a dataset type."""

    return tuple(
        sorted(
            FIELD_CATALOGUES.get(dataset_type, ()),
            key=lambda field: field.display_name.casefold(),
        )
    )
