"""Embedded verifier for the shared technician password.

Generated by tools/configure_technician_password.py. The plaintext password is not stored.
"""

ADMIN_PASSWORD_SALT_HEX = "94f8de2ca2c3d8bfed3257b973c8bd70"
ADMIN_PASSWORD_VERIFIER_HEX = "20dcf0ea3460b760ef5f8011e68686cfbd5304f80fccdfb2ef25955917c10c26"
