"""Embedded verifier for the shared technician password.

Generated by tools/configure_technician_password.py. The plaintext password is not stored.
"""

ADMIN_PASSWORD_SALT_HEX = "f891ca9d1145cf85111ead43f70f961a"
ADMIN_PASSWORD_VERIFIER_HEX = "bf6d5f504a0667492490ff5d46653e86547df710b56557a38e37c81c4052a95f"
