"""Generate the embedded verifier for the shared technician password."""

from __future__ import annotations

import getpass
import secrets
from pathlib import Path

from auditor_support_tool.services.administrator_settings_service import (
    derive_password_verifier,
)

_MINIMUM_PASSWORD_LENGTH = 16
_TARGET = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "auditor_support_tool"
    / "services"
    / "administrator_password_verifier.py"
)


def main() -> int:
    password = getpass.getpass("Shared technician password: ")
    confirmation = getpass.getpass("Confirm technician password: ")

    if password != confirmation:
        raise SystemExit("Passwords do not match.")
    if len(password) < _MINIMUM_PASSWORD_LENGTH:
        raise SystemExit(
            f"Use a technician password of at least {_MINIMUM_PASSWORD_LENGTH} characters."
        )

    salt = secrets.token_bytes(16)
    verifier = derive_password_verifier(password, salt)

    _TARGET.write_text(
        '"""Embedded verifier for the shared technician password.\n\n'
        "Generated by tools/configure_technician_password.py. The plaintext password "
        'is not stored.\n"""\n\n'
        f'ADMIN_PASSWORD_SALT_HEX = "{salt.hex()}"\n'
        f'ADMIN_PASSWORD_VERIFIER_HEX = "{verifier.hex()}"\n',
        encoding="utf-8",
    )

    print(f"Technician-password verifier written to {_TARGET}")
    print("Use the same application build on every installation to keep the password consistent.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
